title: El_photography
url: https://saumil-sh.github.io/el_photo/
baseurl:

author: Saumil Shah
description: A highly automatic jekyll photo gallery.

include: ['_pages']

markdown: kramdown
kramdown:
  input: GFM
